# -*- coding: utf-8 -*-
"""Types(학생용).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e3Lh3oPLFEU2ZPwx3C0-Ac0YHfc5Olc5

<h3 id="exercise">Exercise 1 (Types): Your First Program</h3>
숙제 제출시 반드시 "Exercise 1 (Types) : Your First Program"이라는 것과 함께, 자신의 이름과 학번을 꼭 기재하세요 (comment도 좋고, 아니면 파일이름에라도 좋고)

<p>Generations of programmers have started their coding careers by simply printing "Hello, world!". You will be following in their footsteps.</p>
<p>In the code cell below, use the <code>print()</code> function to print out the phrase: <code>Hello, world!</code></p>
"""

# Write your code below and press Shift+Enter to execute

"""Double-click __here__ for the solution.

<!-- Your answer is below:

print("Hello, world!")

-->
"""

print("Hello, world!")

"""<p>Now, let's enhance your code with a comment. In the code cell below, print out the phrase: <code>Hello, world!</code> and comment it with the phrase <code>Print the traditional hello world</code> all in one line of code.</p>"""

# Write your code below and press Shift+Enter to execute

print("Hello, world!") # Print the traditional hello world

"""Double-click __here__ for the solution.

<!-- Your answer is below:

print("Hello, world!") # Print the traditional hello world

-->

"""